version: "3"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=sample
      - TZ="Asia/Tokyo"
    ports:
      - 54322:5432
